// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE9bJJ8bo_Y1xFBhRcYm-o8ofIds6HX5Q',
    appId: '1:753539490526:web:fdd982f8e86d68c669d84f',
    messagingSenderId: '753539490526',
    projectId: 'universal-yoga-3de7d',
    authDomain: 'universal-yoga-3de7d.firebaseapp.com',
    storageBucket: 'universal-yoga-3de7d.appspot.com',
    measurementId: 'G-BLY11WG2GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yVysuRcl0255tG8FW0TQamMpzkE4n3g',
    appId: '1:753539490526:android:17f6abe34cd1ea2169d84f',
    messagingSenderId: '753539490526',
    projectId: 'universal-yoga-3de7d',
    storageBucket: 'universal-yoga-3de7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApeQOgELwJbtKYOGvvxO5yNuQyQA2dBY0',
    appId: '1:753539490526:ios:8e73a5530c6ef48669d84f',
    messagingSenderId: '753539490526',
    projectId: 'universal-yoga-3de7d',
    storageBucket: 'universal-yoga-3de7d.appspot.com',
    iosBundleId: 'com.example.universalYogaCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApeQOgELwJbtKYOGvvxO5yNuQyQA2dBY0',
    appId: '1:753539490526:ios:8e73a5530c6ef48669d84f',
    messagingSenderId: '753539490526',
    projectId: 'universal-yoga-3de7d',
    storageBucket: 'universal-yoga-3de7d.appspot.com',
    iosBundleId: 'com.example.universalYogaCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE9bJJ8bo_Y1xFBhRcYm-o8ofIds6HX5Q',
    appId: '1:753539490526:web:4857621ef4240a4069d84f',
    messagingSenderId: '753539490526',
    projectId: 'universal-yoga-3de7d',
    authDomain: 'universal-yoga-3de7d.firebaseapp.com',
    storageBucket: 'universal-yoga-3de7d.appspot.com',
    measurementId: 'G-R17GQQ1ELJ',
  );

}